using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace XML.Models
{
    public class TRANDAU
    {
        public string MATRAN { get; set; }
        public string NAM { get; set; }
        public string NGAYTD { get; set; }
        public string VONG { get; set; }
        public string MACLB1 { get; set; }
        public string MACLB2 { get; set; }
        public string MASAN { get; set; }
        public string KETQUA { get; set; }

    }
}